name: Node.js Deploy CI

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Build
      run: |
        npm install
        npm install -g hexo-cli
        npm run build
    - name: Deploy
      run: |
        hexo deploy